version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
      open-pull-requests-limit: 0 # Deactivate Dependabot for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      open-pull-requests-limit: 0 # Deactivate Dependabot for GitHub Actions
